import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { NavBar } from '@/components/UI/navBar';
import { Toaster } from 'sonner';
import { ContextProvider } from '@/context';
import { env } from '@/env';

const inter = Inter({ subsets: ['latin'] });
const title = 'Livestock Information System';
const description = 'Generated by create next app';
const url = env.BASE_URL;

export const metadata: Metadata = {
	metadataBase: new URL(url),
	title,
	description,
	authors: [{ name: 'Shiloh George' }],
	robots: 'index, follow',
	openGraph: {
		title,
		description,
		siteName: 'lis-dev',
	},
	twitter: {
		card: 'summary',
		site: url,
		creator: 'Shiloh George',
		images: '/opengraph-image.png',
	},
	alternates: { canonical: url },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} bg-black text-white font-normal w-full h-screen overflow-hidden text-sm flex-col flex font-sans`}>
				<ContextProvider>
					<NavBar />
					{children}
				</ContextProvider>
				<Toaster
					richColors
					position='bottom-left'
					duration={4000}
					closeButton
					theme={'light'}
				/>
			</body>
		</html>
	);
}
